# -*- mode: ruby -*-
# vi: set ft=ruby :

module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def OS.unix?
    !OS.windows?
  end

  def OS.linux?
    OS.unix? and not OS.mac?
  end
end

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 80, host: 8060, auto_correct: true
  config.vm.network :forwarded_port, guest: 3306, host: 13306, auto_correct: true
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"


  if (defined?(OS.windows)).nil?
    config.vm.synced_folder "../.", "/var/www/babysteps", :mount_options => ["dmode=777", "fmode=666"]
  else
    config.vm.synced_folder "../.", "/var/www/babysteps", :mount_options => ["dmode=777", "fmode=666"], :nfs => true
  end

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpuexecutioncap", "90", "--name", "babysteps.dev"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
end
